### ISSUE TITLE
Reference Particle Helpers

### ISSUE THREAD

**Issue by ax3l** [BLAST-ImpactX/impactx#178]
Let's add helper functions to the reference particle to:
- set energy in MeV
- get energy in MeV, gamma, gamma-1
- get momentum in normalized units, beta*gamma
- get beta

**Comment by cemitch99** [comment]
Already in progress.  Some of these relationships are rather trivial--do we really need separate functions for gamma and gamma-1, and also beta and beta*gamma?  Many of these functions contain only 1 operation.

**Comment by ax3l** [comment]
Good question, gamma and beta appear sufficient, but returning also gamma*beta is numerically more precise to calculate, since beta on its own is always struggling with precision issues.

I agree we can skip gamma-1

**Comment by cemitch99** [comment]
Yes, agreed.  gamma*beta is also frequently used throughout the element functions.

**Comment by cemitch99** [comment]
See PR# 180
