### ISSUE TITLE
Examples: All with a Python Version

### ISSUE THREAD

**Issue by ax3l** [BLAST-ImpactX/impactx#202]
Add a Python version of each example (and show py version first in each example's README).

**Comment by n01r** [comment]
I'm gonna do the Chicane first 👍  -> #207

**Comment by RTSandberg** [comment]
I'll do the multipole example-> #211

**Comment by ax3l** [comment]
Note: Please add a bunch charge to further Python tests: https://github.com/ECP-WarpX/impactx/pull/212 :)

**Comment by RTSandberg** [comment]
I'll do the Kurth and iota lens Python examples, with bunch charge :)

**Comment by ax3l** [comment]
Ok, let's merge #218 next, and then we finalize: 
- [x] Constant Focusing Channel #224
- [x] FODO Cell with RF

**Comment by n01r** [comment]
Constant Focusing Channel --> https://github.com/ECP-WarpX/impactx/pull/224

**Comment by n01r** [comment]
FODO RF --> #237

**Comment by ax3l** [comment]
Wuhu, completed two weeks ago. Thank you so much @n01r and @RTSandberg :rocket: :sparkles:
