### ISSUE TITLE
Plasma Lens Element

### ISSUE THREAD

**Issue by ax3l** [BLAST-ImpactX/impactx#283]
In https://github.com/ECP-WarpX/WarpX/pull/3063, @dpgrote adds a simple plasma lens element.

`plasmalens` for a field modeling a plasma lens
          This applies a radially directed plasma lens field that is uniform within the `z` extent of the element with
          a sharp cut off at the ends.
          This uses residence corrections, with the field scaled by the amount of time within the element for particles entering
          or leaving it, to increase the accuracy.

Let us add the same element as a map to ImpactX.

Is this similar to our `ConstF` element?

**Comment by RemiLehe** [comment]
Sounds good. 
Do I understand correctly that residence correction would not be implemented, in the case of ImpactX, because it is a z-based code, instead of a t-based code?

**Comment by RemiLehe** [comment]
My understanding is that this is very similar to a quadrupole, except that the field is focusing in both `x` and `y`.

**Comment by ax3l** [comment]
Isn't this exactly what we do in the `ConstF` element (and isn't our `ConstF` more general)?

**Comment by ax3l** [comment]
Discussed: `ConstF` is more general than the current WarpX `plasmalens` element. So I will open an issue in WarpX to harmonize :)
https://github.com/ECP-WarpX/WarpX/issues/3566
