### ISSUE TITLE
no attribute 'BeamMonitor' in conda install

### ISSUE THREAD

**Issue by electronsandstuff** [BLAST-ImpactX/impactx#333]
Hey folks, I was trying to get a test example running (specifically the [Constant Focusing Channel](https://impactx.readthedocs.io/en/latest/usage/examples/cfchannel/README.html#constant-focusing-channel) example). I am able to successfully install the package through conda. However, executing the script gives the following error.

```
Traceback (most recent call last):
  File "/home/chris/physics-ml-priors-linux/20230402-impactx-test.py", line 41, in <module>
    monitor = elements.BeamMonitor("monitor", "h5")
AttributeError: module 'impactx.impactx_pybind.elements' has no attribute 'BeamMonitor'
```

**Comment by ax3l** [comment]
Hi @electronsandstuff , thanks for reaching out!

I am about to release the latest version (23.04) on conda in the coming days, which adds the `BeamMonitor` element. You currently still get `23.02` from conda.

* 22.04 features: https://impactx.readthedocs.io/en/23.04/
* 22.02 features: https://impactx.readthedocs.io/en/23.02/

Sorry for the confusion that this caused :) Will ping you here when the release is also on Conda!

Until then, you can use the constant focusing channel example as documented in 23.02, which uses ASCII diagnostics (replaced in 23.04 with openPMD beam monitor diagnostics):
https://impactx.readthedocs.io/en/23.02/usage/examples/cfchannel/README.html

**Comment by electronsandstuff** [comment]
Ahhh, I'm too early. Thanks, and looking forward to the release!

**Comment by ax3l** [comment]
Nearly there... :)
Finalizing the conda package in https://github.com/conda-forge/impactx-feedstock/pull/14

**Comment by ax3l** [comment]
@electronsandstuff the `23.04` release is now also on conda.

It will take about 1-2 more hours to become available, after that you can install it and give it a try! Let us know if this works for you :)

**Comment by electronsandstuff** [comment]
Wow, that was fast! Looks like it's working on my side now. Thanks @ax3l!

**Comment by ax3l** [comment]
This is awesome, glad to hear @electronsandstuff! :tada: 

Let us know how you like it, what is missing, or if you like to add anything. More to come from our side as well, happy to involve you :)

**Comment by ax3l** [comment]
Just FYI, we will do a couple of follow-ups that we indicated in the PR description of #299 in the coming release.

First PR will be #349 to complete meta-data for standard conformance.
