### ISSUE TITLE
Apertures & Lost Particle Book Keeping

### ISSUE THREAD

**Issue by ax3l** [BLAST-ImpactX/impactx#394]
We can add apertures to ImpactX.

Programmatically, we will set particles that are to be removed to a negative `id`.
They will then the removed during the communication step by AMReX.

If we want to keep track of lost particles (6D position of particle in lattice when removed), we would process these particles before the communication is called. This is a useful functionality to have as well.

Mad-X reference:
- radially symmetric
- rectangular
- elliptical

**Comment by cemitch99** [comment]
Three options for application of the aperture boundary:

1) A thin "aperture" element, whose purpose is to compare particles against the aperture boundary (available in TraceWin, MAD-X)
2) Adding aperture restrictions to all existing elements (currently used in IMPACT-Z)
3) Allowing the user to provide a file of the form (s, xmax, ymax, type) specifying the aperture boundary vs s.

**Comment by ax3l** [comment]
General support for option 1 added in #398, part of release `23.12`.

GPU support tracked in #499
