### ISSUE TITLE
Check handling of low-energy beams

### ISSUE THREAD

**Issue by cemitch99** [BLAST-ImpactX/impactx#435]
Calculations show errors in fields for beams with very low energy (eg, electrons << 1 MeV).

Double-check, eg, normalization factors of beta that become important at very low energy.

**Comment by ax3l** [comment]
We believe this is resolved.
While testing three weeks ago for our space charge benchmarks, we mismatched kinetic and total energy in one of our input files.

We could rename the `set_energy`  and `energy` parameters in input files to `set_kin_energy` to be explicit (currently only the doc string reveals this detail). I'll post a PR: #446
