### ISSUE TITLE
Impact_X_surrogate_model_definitions

### ISSUE THREAD

**Issue by mehdiabedi1234** [BLAST-ImpactX/impactx#534]
Dear Sir:
I  am going to use ImpactX, I have run examples but I got the below error:
"C:\Mehdi\E\impactx\Untitled-6.py", line 22, in <module>
    from surrogate_model_definitions import surrogate_model
ModuleNotFoundError: No module named 'surrogate_model_definitions'
Do you know how I can fix it? 
Thank you for your response in advance.
Sincerely yours,
Mehdi

**Comment by RTSandberg** [comment]
Hi Mehdi,

There is another file in the example directory you will need to copy or download, `surrogate_model_definitions.py`

**Comment by mehdiabedi1234** [comment]
Thank you for your response. I installed impactx on windows 10 , I always have the below error:
 
  File "C:\Users\mabed\anaconda3\envs\impactx\Lib\site-packages\impactx\__init__.py", line 16, in <module>
    os.add_dll_directory(p)
  File "<frozen os>", line 1125, in add_dll_directory
OSError: [WinError 87] The parameter is incorrect: '.'

How can I solve this problem? 
Thank you for your help.

**Comment by mehdiabedi1234** [comment]
Thank you for your response. I installed impactx on windows 10 , I always have the below error:

File "C:\Users\mabed\anaconda3\envs\impactx\Lib\site-packages\impactx_init_.py", line 16, in
os.add_dll_directory(p)
File "", line 1125, in add_dll_directory
OSError: [WinError 87] The parameter is incorrect: '.'

How can I solve this problem?
Thank you for your help.

**Comment by ax3l** [comment]
Oh, that is unusual. Can you please open the file that throws the error with a text editor?
It corresponds to this file:
  https://github.com/ECP-WarpX/impactx/blob/development/src/python/impactx/__init__.py

Can you edit this line
https://github.com/ECP-WarpX/impactx/blob/195c38c0522a6659fe5749df323680bfe1abb340/src/python/impactx/__init__.py#L15

to read
```py
        if os.path.exists(p) and p != ".":
```
and try again?
