### ISSUE TITLE
install with conda error: Symbol not found: __ZN5amrex6OpenMP9omp_locksE

### ISSUE THREAD

**Issue by tiamiceli** [BLAST-ImpactX/impactx#550]
My computer: MacBook Pro M1 (2020), MacOS: 13.6.4
My environment: 
- no mpi or hdf5 in /usr/local/lib, only docker
- conda installed: openmpi (not installed pre-req), impactx
- I made a new environment, see this in my environment yaml:
```
name: impactx
channels:
  - conda-forge
dependencies:
  - conda-forge::openmpi
  - impactx
```

Error:
```
(impactx) miceli@AD138348-MLT sample_impactX % mpirun -np 1 impactx.NOMPI.OMP.DP.OPMD input_fodo.in 
dyld[38475]: Symbol not found: __ZN5amrex6OpenMP9omp_locksE
  Referenced from: <8E44EFB0-2EDB-3ED4-A55C-9E3BB0D70ECE> /opt/miniconda3/envs/impactx/bin/impactx.NOMPI.OMP.DP.OPMD
  Expected in:     <C065B295-33E2-3870-8CD8-4CD11097D6AC> /opt/miniconda3/envs/impactx/lib/libamrex_3d.dylib
--------------------------------------------------------------------------
prterun noticed that process rank 0 with PID 38475 on node AD138348-MLT exited on
signal 9 (Killed: 9).
--------------------------------------------------------------------------
```

**Comment by ax3l** [comment]
Hi @tiamiceli,

Thank you for the report!

Oh no, we are aware of this issue since https://github.com/AMReX-Codes/amrex/pull/3696 for Windows, but did not know it also affects macOS!

We work on a fix with @WeiqunZhang in https://github.com/AMReX-Codes/amrex/pull/3798

**Comment by ax3l** [comment]
Confirmed: on my mac mini (M1) using
```bash
conda create -n impactx -c conda-forge impactx
conda activate impactx 
```
[as documented](https://impactx.readthedocs.io/en/latest/install/users.html).

And then
```console
$ impactx.NOMPI.OMP.DP.OPMD 
dyld[85863]: Symbol not found: __ZN5amrex6OpenMP9omp_locksE
  Referenced from: /Users/axel/miniconda3/envs/impactx/bin/impactx.NOMPI.OMP.DP.OPMD
  Expected in: /Users/axel/miniconda3/envs/impactx/lib/libamrex_3d.dylib
Abort trap: 6
```

**Comment by ax3l** [comment]
Oh, that is actually because it already uses the conda package `amrex nompi_h39290d2_102` and I changed the exported OpenMP symbol in this update compared to what ImpactX was built against, `amrex nompi_h39290d2_101`.

Fix coming via https://github.com/conda-forge/impactx-feedstock/commit/7ad786c6fef06311929e8edadcb1c2ae413af013

Tomorrow, recreating the environment should fix the issue on macOS @tiamiceli.

(@WeiqunZhang the Windows issue is still unsolved for us.)

**Comment by ax3l** [comment]
@tiamiceli I gave the new package a test:
```bash
conda env remove -n impactx

conda create -n impactx -c conda-forge impactx
conda activate impactx 
```
(installs now `impactx            conda-forge/osx-arm64::impactx-24.03-py312h55a178e_1`)

With that macOS works again :tada: 
```console
$ impactx.NOMPI.OMP.DP.OPMD ~/src/impactx/examples/fodo/input_fodo.in
Initializing AMReX (24.03)...
OMP initialized with 8 OMP threads
AMReX (24.03) initialized

Grids Summary:
  Level 0   1 grids  512 cells  100 % of domain
...
```

Does this fix it for you as well? :)

**Comment by ax3l** [comment]
@tiamiceli does everything work now? :)
