### ISSUE TITLE
How to make test run

### ISSUE THREAD

**Issue by zhangli28** [BLAST-ImpactX/impactx#579]
Hi,

after installing ImpactX, now I want to run some example PYTHON scripts. 
I need to submit the job with a job script file. 

yesterday, I build using the following command

```
cmake -DMPI_C_COMPILER=/sqfs/home/zhangli4/conda_env/impactx-cpu/bin/mpicc -DMPI_CXX_COMPILER=/sqfs/home/zhangli4/conda_env/impactx-cpu/bin/mpicxx -S . -B build -DImpactX_MPI=OFF -DImpactX_PYTHON=ON -DPython_EXECUTABLE=/sqfs/home/zhangli4/conda_env/impactx-cpu/bin/python
```

It created a directory with name **build/bin** . Inside bin, there are some executables. Out of them, two are **impactx** and **impactx.NOMPI.OMP.DP.OPMD**

To run the example PYTHON scripts, I created a folder **Test_python**. I copied both **impactx** and **impactx.NOMPI.OMP.DP.OPMD** in this directory. I also copy the **run_chicane.py** file in the same folder. 

In the job script file, what command I should use to simulate the **run_chicane.py** file ?

**Comment by zhangli28** [comment]
Hi @n01r , I can run the **input_chicane.in** file with the command
```
./inmpactx input_chicane.in
```
But I want to run **run_chicane.py** file

**Comment by n01r** [comment]
Hi @zhangli28,

To create your app binaries `impactx.*` you executed 
```Shell
# compile, here we use four threads
cmake --build build -j 4
``` 
In https://impactx.readthedocs.io/en/latest/install/cmake.html#compile, we also mention that you can install the Python bindings the following way
```Shell
#   this installs the Python bindings via "python3 -m pip install ..."
cmake --build build --target pip_install -j 4
```
Just load up your environment and execute this command using the same `build` directory where you already installed the binaries successfully. :slightly_smiling_face: 

Our examples also have their own documentation, and for the chicane example the command is just `python3 run_chicane.py` (see https://impactx.readthedocs.io/en/latest/usage/examples/chicane/README.html#run), given that your environment is loaded and the Python you are using is the one where the `impactx` module was installed to.

**Comment by zhangli28** [comment]
Hi @n01r , thank you. It worked ! 

However, the data file was not save. **Looks like we build openmpd api without HDF5.**

The output message is

```
Initializing AMReX (24.04)...
OMP initialized with 40 OMP threads
AMReX (24.04) initialized

Grids Summary:
  Level 0   1 grids  512 cells  100 % of domain

Traceback (most recent call last):
  File "/sqfs/home/zhangli4/Year2024/ImpactX/Test1/run_chicane.py", line 47, in <module>
    monitor = elements.BeamMonitor("monitor", backend="h5")
RuntimeError: Wrong API usage: openPMD-api built without support for backend 'HDF5'.


TinyProfiler total time across processes [min...avg...max]: 0.01943 ... 0.01943 ... 0.01943

-------------------------------------------------------------------------------------------
Name                                        NCalls  Excl. Min  Excl. Avg  Excl. Max   Max %
-------------------------------------------------------------------------------------------
ImpactX::add_particles                           1   0.004124   0.004124   0.004124  21.22%
ImpactX::AddNParticles                           1  0.0004255  0.0004255  0.0004255   2.19%
DistributionMapping::SFCProcessorMapDoIt()       1  1.666e-05  1.666e-05  1.666e-05   0.09%
AmrMesh::MakeDistributionMap()                   1  1.312e-05  1.312e-05  1.312e-05   0.07%
DistributionMapping::Distribute()                1  4.317e-06  4.317e-06  4.317e-06   0.02%
-------------------------------------------------------------------------------------------

-------------------------------------------------------------------------------------------
Name                                        NCalls  Incl. Min  Incl. Avg  Incl. Max   Max %
-------------------------------------------------------------------------------------------
ImpactX::add_particles                           1   0.004549   0.004549   0.004549  23.41%
ImpactX::AddNParticles                           1  0.0004255  0.0004255  0.0004255   2.19%
AmrMesh::MakeDistributionMap()                   1  3.409e-05  3.409e-05  3.409e-05   0.18%
DistributionMapping::SFCProcessorMapDoIt()       1  2.098e-05  2.098e-05  2.098e-05   0.11%
DistributionMapping::Distribute()                1  4.317e-06  4.317e-06  4.317e-06   0.02%
-------------------------------------------------------------------------------------------
Pinned Memory Usage:
----------------------------------------------------------------
Name                            Nalloc  Nfree   AvgMem    MaxMem
----------------------------------------------------------------
The_Pinned_Arena::Initialize()       1      1  751 KiB  8192 KiB
----------------------------------------------------------------

AMReX (24.04) finalized
                           
```

**Comment by zhangli28** [comment]
Hi @n01r , **Finally done with HDF5.** 

Now there are some files in **diags** folder. Let me try to understand what is inside it and how to make some plots.

**Comment by zhangli28** [comment]
@n01r , now I can even see the plots. 

Thank you for outstanding help. I may have many questions more about plotting argument / parameters. I will ask again later.

Thank you so much.

**Comment by n01r** [comment]
Yea, cool, feel free to also suggest if things are missing or could be clearer in our documentation. :slightly_smiling_face: 
Happy accelerator modeling! :rocket:
