### ISSUE TITLE
IMPACT-T vs ImpactX

### ISSUE THREAD

**Issue by laxmisubramanyam** [BLAST-ImpactX/impactx#598]
Hi, 

what is difference between impact-T and impact-X ?

Thanks

**Comment by n01r** [comment]
Hi @laxmisubramanyam, thank you for your question!

Our general strategy modernizes the [BLAST suite of codes](https://blast.lbl.gov) for the Exascale era, putting the expertise and advanced numerics embedded in codes like Warp, IMPACT-T and IMPACT-Z on a new platform (using CMake, C++, and Python and supporting now both GPUs and CPUs), with unified input frameworks, and to facilitate modeling of upcoming hybrid conventional-and-plasma accelerator beamlines.

[IMPACT-T](https://github.com/impact-lbl/IMPACT-T) is an established **time-based** (t-based) code for tracking of relativistic charged particles. It is fully 3D, features space-charge, short-range wakefields, coherent synchrotron radiation, etc. It is written in Fortran and works on laptops/desktop computers and supercomputers using CPUs.
[WarpX](https://warpx.readthedocs.io) is our new time-based PIC code for GPUs and CPUs (electro-static and electromagnetic) and will mid-term also include all IMPACT-T features.

[ImpactX](https://impactx.readthedocs.io/) is a new-generation **reference-trajectory-based** (s-based) code for tracking of relativistic beam dynamics. It is also 3D, features space-charge, element-wise symplectic integrators, and is a conceptual successor of [IMPACT-Z](https://github.com/impact-lbl/IMPACT-Z).

Please feel free to read up on the details in the slide deck and arxiv papers below. :slightly_smiling_face: 
- [Advanced Particle Accelerator Modeling on Exascale-Class Supercomputers](https://www.olcf.ornl.gov/wp-content/uploads/2022-OLCF-User-Meeting-WarpX-Huebl.pdf) (slides)
- [From Compact Plasma Particle Sources to Advanced Accelerators with Modeling at Exascale](https://arxiv.org/pdf/2303.12873) (AAC22)
- [Next Generation Computational Tools for the Modeling and Design of Particle Accelerators at Exascale](https://arxiv.org/pdf/2208.02382) (NAPAC22)
- [Community Modeling Tools for High Brightness Beam Physics](https://accelconf.web.cern.ch/hb2023/papers/tua2i2.pdf) (HB2023)

**Comment by laxmisubramanyam** [comment]
Hi @n01r , 

thanks for being pretty clear with detailed information. I am looking for a beam-line code with coherent synchrotron radiation (CSR) effect. Which code do you recommend for this ?

Thanks.
Laxmi

**Comment by n01r** [comment]
Hi @laxmisubramanyam, can you give more specifics about the project, e.g., what beamline elements you need and what beams you would like to model? (Beam dimensions, energy spread, should it include source modeling?)

**Comment by laxmisubramanyam** [comment]
Hi @n01r, 

I am working for a project, which is oriented towards simulating an entire beam line. This basically includes a set of quadrupoles and chicane. We are looking for a reliable code that can give us, as accurate as possible, the effect of CSR on electron beam phase-space during the bunch compression part. The energy of the electron bunch will be in the range of ~ 180 MeV, energy spread is about 5.0e-3, electron beam transverse size std_x,y = 50.0e-6, and longitudinal size std_tau = 0.75e-3 and of course some chirp for efficient bunch compression in chicane.

**Comment by n01r** [comment]
Thank you for these details!
We currently have someone working on the implementation of 1D wakefield effects and CSR will be at the top of the list once this is in.

Therefore, ImpactX does not currently have this capability just yet. IMPACT-Z and IMPACT-T both have it, if you want to get started directly. Looking at the setup outlined above, @qianglbl and @cemitch99, what would you recommend? :slightly_smiling_face:

**Comment by qianglbl** [comment]
Hi  @laxmisubramanyam,

I would recommend using Impact-Z code for your problem.

Best,
Ji

**Comment by laxmisubramanyam** [comment]
Hi @n01r and @qianglbl,

thanks for your quick reply. Please, could you confirm if this is the GitHub site for Impact-Z code https://github.com/impact-lbl/IMPACT-Z.

**Comment by qianglbl** [comment]
@laxmisubramanyam
Yes, it is.
You can modify the input file in example 3 for your application.

Ji

**Comment by laxmisubramanyam** [comment]
@qianglbl 

thanks. I will check it. Does it have any documentation ?

**Comment by qianglbl** [comment]
https://github.com/impact-lbl/IMPACT-Z/tree/master/doc

**Comment by laxmisubramanyam** [comment]
@qianglbl 

Thank you.
Laxmi

**Comment by laxmisubramanyam** [comment]
Hi @qianglbl @n01r @ax3l,

On main page of ImpactX it is written that ```mpactX: an s-based beam dynamics code including space charge effects. This is the next generation of the IMPACT-Z code```. 

If it is so, then why you refer me to use Impact-Z and not Impact-X ? I expect that if Impact-X is an advance code than Impact-Z, it should include reliable CSR effects also. Isn't it ?

**Comment by cemitch99** [comment]
Hi @laxmisubramanyam,
ImpactX is a new code that is under active development.  It does not currently include CSR effects, but these will be implemented in the near future.  (We have a student who has begun work on this topic.)

**Comment by laxmisubramanyam** [comment]
Hi @cemitch99, 

Thanks a lot for the update. Actually, I tried some examples of Imapact-X and like the compactness of the scripts. However, the user interface or input is not so simple but a bit complicated. I was also wondering that you have a wonderful team of developers (including the developers of Impact-Z), then why CSR is missing. After your update, I am looking forward for the more advance features in the near future. 

Best wishes to the entire team,
Laxmi
