### ISSUE TITLE
Initial checks for beam distribution

### ISSUE THREAD

**Issue by koesterf** [BLAST-ImpactX/impactx#614]
Hi,

It might be useful to check the initial beam distribution before running the final simulation. I would like to request to some plotting availability to check initial distribution like:

(1) x-px, y-py [trasnverse phase-space],
(2) longitudinal phase-space [t-pt (if this is longitudinal phase space)],
(3) beam distribution in x-y space,
(4) beam current

This is helpful to check if the initial beam setup is correct or not. 
Also, the present beam data is hard to read and understand.

**Comment by ax3l** [comment]
Hi @koesterf ,

Thanks for the question!

Do you already see our [data analysis chapter](https://impactx.readthedocs.io/en/latest/dataanalysis/dataanalysis.html) in the manual?

For initial beam distribution checks, you can plot the beam moments of the first step (#614), or add a [BeamMonitor](https://impactx.readthedocs.io/en/latest/usage/python.html#impactx.elements.impactx.elements.BeamMonitor) element as the first element of your beamline ([example](https://impactx.readthedocs.io/en/latest/usage/examples/fodo/README.html)), or plot interactively from Python before running `sim.evolve()`: https://impactx.readthedocs.io/en/latest/dataanalysis/dataanalysis.html#interactive-analysis

Does this help?

>  Also, the present beam data is hard to read and understand.

Thanks for the comment, we will add more output data documentation for it in #618.

For input, we recently improved [these pages](https://impactx.readthedocs.io/en/latest/theory/beam_distribution.html). Please let us know if you find something missing and/or if more info would be helpful.
