### ISSUE TITLE
Parameter conversion

### ISSUE THREAD

**Issue by hnakahara79** [BLAST-ImpactX/impactx#615]
Hi friends,

I am preparing an input file as required for ImpactX. Can you please check the attached file and say if I am converting the parameters correctly so that I can use them in impact input file. 

Thanks in advance.
Naka

**Comment by ax3l** [comment]
Hi @hnakahara79 ,

That looks correct to me.

@cemitch99 and @n01r recently added more details in the documentation page on https://impactx.readthedocs.io/en/latest/theory/beam_distribution.html which shows the same relations as the ones you arrive on :+1: I'll ping them for a 2nd set of eyes.

**Comment by cemitch99** [comment]
Hi @hnakahara79,

All the expressions related to X and Y are correct.  For the expressions related to the longitudinal variables, does $\sigma_p$ here denote the rms value of the relative momentum deviation $\Delta p/p_{\rm ref}$, after taking out the linear correlation with $\tau$ (uncorrelated)?  If so, then your expression for $\beta_t$ is correct, but $\gamma_t$ is not.  (You can see that the expression is dimensionless, while $\gamma_t$ should have units of 1/m.)  If you work out $\alpha_t$ the correct expression is $\alpha_t$=- chirp ($\beta_t$), and you can obtain $\gamma_t$ from that.

The expressions related the Twiss functions to the ImpactX input parameters are all correct.

**Comment by hnakahara79** [comment]
Hi @ax3l , @cemitch99 

thanks for checking the relations. 

If you accept, I have one suggestion. Why don't you include some comparison with ASTRA, Impact-T, Ocelot and CSRtrack. This will be great. I have seen people are doing such comparison in conferences. 

best wishes,
Naka
