### ISSUE TITLE
[Dashboard] Distributions via Twiss

### ISSUE THREAD

**Issue by ax3l** [BLAST-ImpactX/impactx#724]
Let's change all the distribution input to only accept CS/Twiss parameters.

Example:
- https://impactx.readthedocs.io/en/latest/usage/examples/distgen/README.html#a-6d-gaussian-distribution-from-twiss-functions
- https://github.com/ECP-WarpX/impactx/blob/development/src/python/impactx/distribution_input_helpers.py#L12-L25

I propose to fully replace the `lambda=..` input and only support the twiss parameters. To discuss with @cemitch99 and @n01r

**Comment by n01r** [comment]
I would be in favor.  :+1: 
I still like offering helper functions that transform other common inputs to our input conventions but I am for moving towards CS/Twiss parameters as the new default.

**Comment by ax3l** [comment]
Yes, and for the dashboard I would only offer CS/Twiss for now, no alternatives.
